language: java

addons:
  ssh_known_hosts:
  - doulos.iakob.com

script:
- mvn clean install

before_deploy:
- openssl aes-256-cbc -K $encrypted_540ff0d5f95e_key -iv $encrypted_540ff0d5f95e_iv
  -in .travis/deploy.pem.enc -out .travis/deploy.pem -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.pem
- ssh-add .travis/deploy.pem
- git remote add deploy dokku@doulos.iakob.com:lessonmanager
- git config --global push.default simple

deploy:
- provider: script
  skip_cleanup: true
  script: git push deploy master
  on:
    branch: master
